### ISSUE TITLE
Identify and add resources

### ISSUE THREAD

**Issue by trallard** [numfocus/getting-started-with-open-source#21]
Have you come across other useful resources to get started into the world of Open Source?
Why not add them to our [List of curated resources](https://github.com/numfocus/getting-started-with-open-source/blob/master/compilation_of_open_source_resources.md)?

**Comment by copperwiring** [comment]
@trallard  Wish to add Outreachy as one of the places where can contribute. 
Also, could we add video resources which guide people to help start with open source?

**Comment by trallard** [comment]
I think this is an amazing idea!!! Would you like to submit a Pull Request for this @copperwiring ?

**Comment by copperwiring** [comment]
I would love to. Thanks.

**Comment by thegautamkumarjaiswal** [comment]
Hi, @trallard I want to work on this issue and I will add more open source programs (like - GirlScript soc, LetGrowMore soc, Pclub soc, MLH fellowship and more)and organizations.

**Comment by trallard** [comment]
Hey @thegautamkumarjaiswal that would be great 👍🏽

**Comment by thegautamkumarjaiswal** [comment]
Yes I updated, please merge this pr. #33

**Comment by trallard** [comment]
Closed thanks to @thegautamkumarjaiswal
